blank_issues_enabled: false
contact_links:
  - name: Support & usage queries
    url:  https://vscode-dev-community.slack.com/archives/C011NUFTHLM
    about: For general support queries please use this slack channel
