name: Build
on:
  push:
    branches:
      - '**'
  release:
    types: [published]

jobs:
  analyse:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Use Java 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          architecture: x64
      - name: Install Node Packages
        run: npm ci
      - name: Lint Files
        run: npm run lint
      - name: Build Java
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
          build-root-directory: java-gradle-tasks
          wrapper-directory: java-gradle-tasks
        if: github.ref != 'master'
      - name: SonarQube Analyse
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_SONARCLOUD_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          JAVA_HOME: ''
        if: github.ref != 'master'

  build-jar-artifacts:
    needs: [analyse]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Use Java 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          architecture: x64
      - name: Build lib
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build copyLibToParent
          build-root-directory: java-gradle-tasks
          wrapper-directory: java-gradle-tasks
      - name: Upload lib
        uses: actions/upload-artifact@v1
        with:
          name: lib
          path: lib

  test-extension:
    needs: [build-jar-artifacts]
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x]
        java-version: ['8', '12.0.2']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Download lib
        uses: actions/download-artifact@v1
        with:
          name: lib
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use Java ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
          architecture: x64
      - name: Start Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        if: matrix.os == 'ubuntu-latest'
      - name: Set perms
        run: |
          chmod +x lib/gradle-tasks
          unset npm_config_prefix
        if: matrix.os != 'windows-latest'
      - name: Build & test extension on ${{ matrix.os }}
        run: |
          npm ci
          npm test
        env:
          DISPLAY: ':99.0'
          CI: 'true'

  publish-extension:
    needs: [test-extension]
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Download lib
        uses: actions/download-artifact@v1
        with:
          name: lib
      - name: Move files to extension
        run: |
          mv lib extension/
          mv images extension/
          mv README.md extension/
      - name: Move lib to extension
        run: mv lib extension/
      - name: Package extension
        run: |
          cp README.md extension/
          cd extension
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Package extension
        run: |
          chmod +x lib/gradle-tasks
          tag=${GITHUB_REF#refs/tags/}
          echo "Setting package version $tag"
          npm --no-git-tag-version version "$tag"
          npm ci
          npx vsce package
      - name: Publish extension to marketplace
        env:
          AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
        run: |
          npx vsce publish -p "$AZURE_TOKEN"
