name: Node CI Test

on: push

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019]
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-java@v1
        with:
          java-version: '12.0.2'
          architecture: x64
      - name: Setup Linux
        run: |
          apt-get install xvfb
          export DISPLAY=':99.0'
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        if: runner.os == 'Linux'
      - name: Build & test extension
        shell: pwsh
        run: |
          npm ci
          npm run lint
          npm test
