name: Publish extension
on:
  release:
    types: [published]

jobs:
  build-lib:
    name: Build Jar & proto libs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Java 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          architecture: x64
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Build Java lib
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: generateLib
          build-root-directory: java-gradle-tasks
          wrapper-directory: java-gradle-tasks
      - name: Build proto lib
        run: |
          sudo apt-get install protobuf-compiler -y
          npm ci
          npm run compile:proto
      - name: Upload lib
        uses: actions/upload-artifact@v1
        with:
          name: lib
          path: lib

  publish-extension:
    needs: [build-lib]
    name: Publish extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Download lib
        uses: actions/download-artifact@v1
        with:
          name: lib
      - name: Publish extension
        env:
          AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
        run: |
          chmod +x lib/gradle-tasks-server
          tag=${GITHUB_REF#refs/tags/}
          echo "Setting package version $tag"
          npm --no-git-tag-version version "$tag"
          npm ci
          npm run build
          npx vsce publish -p "$AZURE_TOKEN"
